version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      # Настройки PostgreSQL (внутри контейнера)
      POSTGRES_DB: ${POSTGRES_DB:-coffeeshop}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}

      # Настройки Spring Boot
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/${POSTGRES_DB:-coffeeshop}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-secret}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

      # Другие переменные
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    command: >
      sh -c "
      echo 'Запуск PostgreSQL...' &&
      docker-entrypoint.sh postgres &
      sleep 10 &&  # Ожидание инициализации БД
      echo 'Запуск Spring Boot...' &&
      java -jar /app.jar
      "