version: '3.8'

services:
  db:
    image: postgres:15
    restart: always  # Важно для Render (перезапуск при падении)
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    # volumes:  # Не работает на Render без Persistent Disk
    #   - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      # Другие переменные Spring Boot, если нужны

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - app
    restart: always
    ports:
      - "3000:80"  # Render сам назначает порт, это можно удалить